
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidmkiLCJpYXQiOjE2MjQ4MDgxMzl9.1QXtT69jgxTk7SzaesMUtED5gEVPkIHdUgQclZiT8-E


#####

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": " "
}

#####

DELETE http://localhost:4000/logout
Content-Type: application/json
{
    "token": ""
}
#####

POST http://localhost:4000/login 
Content-Type: application/json

{
    "username": "hong"
}